In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("Automobile_data.csv")

In [3]:
data.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19     3.4              10.0        102      5500       24   
4         mpfi  3.19     3.4               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [4]:
df = data.drop(["aspiration","num-of-doors","wheel-base","length","curb-weight","num-of-cylinders","fuel-system","bore","stroke","compression-ratio","peak-rpm"], axis = 1, inplace = True)

In [5]:
data

symboling normalized-losses         make fuel-type   body-style  \
0            3                 ?  alfa-romero       gas  convertible   
1            3                 ?  alfa-romero       gas  convertible   
2            1                 ?  alfa-romero       gas    hatchback   
3            2               164         audi       gas        sedan   
4            2               164         audi       gas        sedan   
..         ...               ...          ...       ...          ...   
200         -1                95        volvo       gas        sedan   
201         -1                95        volvo       gas        sedan   
202         -1                95        volvo       gas        sedan   
203         -1                95        volvo    diesel        sedan   
204         -1                95        volvo       gas        sedan   

    drive-wheels engine-location  width  height engine-type  engine-size  \
0            rwd           front   64.1    48.8        dohc          130   
1            rwd           front   64.1    48.8        dohc          130   
2            rwd           front   65.5    52.4        ohcv          152   
3            fwd           front   66.2    54.3         ohc          109   
4            4wd           front   66.4    54.3         ohc          136   
..           ...             ...    ...     ...         ...          ...   
200          rwd           front   68.9    55.5         ohc          141   
201          rwd           front   68.8    55.5         ohc          141   
202          rwd           front   68.9    55.5        ohcv          173   
203          rwd           front   68.9    55.5         ohc          145   
204          rwd           front   68.9    55.5         ohc          141   

    horsepower  city-mpg  highway-mpg  price  
0          111        21           27  13495  
1          111        21           27  16500  
2          154        19           26  16500  
3          102        24           30  13950  
4          115        18           22  17450  
..         ...       ...          ...    ...  
200        114        23           28  16845  
201        160        19           25  19045  
202        134        18           23  21485  
203        106        26           27  22470  
204        114        19           25  22625  

[205 rows x 15 columns]

In [6]:
# Replacing "?" sign from column "normalized-losses" with np.nan
data["normalized-losses"].replace("?",np.nan, inplace = True)

# coverting column "normalized losses" to float type
data["normalized-losses"] = data["normalized-losses"].astype(float)

# Taking mean of column "normalized-losses" 
losses_mean = data["normalized-losses"].mean()

# Replacing all np.nan with mean just calculated
data["normalized-losses"].fillna(losses_mean,inplace = True)

In [7]:
# Doing same operations as above on column "horsepower"

data["horsepower"].replace("?",np.nan, inplace = True)

data["horsepower"] = data["horsepower"].astype(float)

horsepower_mean = data["horsepower"].mean()

data["horsepower"].fillna(horsepower_mean,inplace = True)

In [8]:
data.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [9]:
data["price"].value_counts()

?        4
7775     2
7898     2
18150    2
8921     2
        ..
15998    1
17669    1
10795    1
34184    1
12290    1
Name: price, Length: 187, dtype: int64

In [10]:
# Doing same operations as above on column "price"

data["price"].replace("?",np.nan, inplace = True)

data["price"] = data["price"].astype(float)

price_mean = data["price"].mean()

data["price"].fillna(price_mean,inplace = True)

In [11]:
data.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

In [12]:
data_num = data.select_dtypes(["int64","float64","int32"])
data_cat = data.select_dtypes(["object"])

In [13]:
data_num.head()

symboling  normalized-losses  width  height  engine-size  horsepower  \
0          3              122.0   64.1    48.8          130       111.0   
1          3              122.0   64.1    48.8          130       111.0   
2          1              122.0   65.5    52.4          152       154.0   
3          2              164.0   66.2    54.3          109       102.0   
4          2              164.0   66.4    54.3          136       115.0   

   city-mpg  highway-mpg    price  
0        21           27  13495.0  
1        21           27  16500.0  
2        19           26  16500.0  
3        24           30  13950.0  
4        18           22  17450.0

In [14]:
data_cat.head()

make fuel-type   body-style drive-wheels engine-location engine-type
0  alfa-romero       gas  convertible          rwd           front        dohc
1  alfa-romero       gas  convertible          rwd           front        dohc
2  alfa-romero       gas    hatchback          rwd           front        ohcv
3         audi       gas        sedan          fwd           front         ohc
4         audi       gas        sedan          4wd           front         ohc

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
for col in data_cat:
    le = LabelEncoder()
    data_cat[col] = le.fit_transform(data_cat[col])

C:\Users\DELL\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [17]:
data_cat.head()

make  fuel-type  body-style  drive-wheels  engine-location  engine-type
0     0          1           0             2                0            0
1     0          1           0             2                0            0
2     0          1           2             2                0            5
3     1          1           3             1                0            3
4     1          1           3             0                0            3

In [18]:
data_new = pd.concat([data_cat,data_num],axis = 1)

In [19]:
data_new.head()

make  fuel-type  body-style  drive-wheels  engine-location  engine-type  \
0     0          1           0             2                0            0   
1     0          1           0             2                0            0   
2     0          1           2             2                0            5   
3     1          1           3             1                0            3   
4     1          1           3             0                0            3   

   symboling  normalized-losses  width  height  engine-size  horsepower  \
0          3              122.0   64.1    48.8          130       111.0   
1          3              122.0   64.1    48.8          130       111.0   
2          1              122.0   65.5    52.4          152       154.0   
3          2              164.0   66.2    54.3          109       102.0   
4          2              164.0   66.4    54.3          136       115.0   

   city-mpg  highway-mpg    price  
0        21           27  13495.0  
1        21           27  16500.0  
2        19           26  16500.0  
3        24           30  13950.0  
4        18           22  17450.0

## Baseline Model

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [21]:
X = data_new.drop("price",axis = 1)
y = data_new["price"]

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [23]:
lin = LinearRegression()

lin.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
lin.score(X_test, y_test)

0.7875361466494448

In [25]:
lin.coef_

array([-1.90468510e+02, -9.76094161e+02, -2.57276711e+02,  1.73696237e+03,
        1.60611355e+04,  2.53555424e+02,  6.61610996e+01,  1.08790884e-01,
        8.04026538e+02,  3.68148230e+02,  9.76722827e+01, -1.15729342e+01,
        2.15004305e+02, -3.65404856e+02])

## Lasso (L1) & Ridge (L2) Rgularization

In [26]:
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

In [27]:
for i in range(50):
    l2 = Ridge(alpha = i)
    l2.fit(X_train, y_train)
    print(i,":",l2.score(X_test,y_test))

0 : 0.7875361466494459
1 : 0.7981012877810147
2 : 0.8016757159278609
3 : 0.8033912649254833
4 : 0.8043688747747944
5 : 0.8049784833479037
6 : 0.8053760280979319
7 : 0.8056389413104093
8 : 0.8058104284127557
9 : 0.8059167648050932
10 : 0.8059750068066344
11 : 0.8059967986375096
12 : 0.8059904109740483
13 : 0.805961906989603
14 : 0.8059158466418461
15 : 0.8058557318657851
16 : 0.8057842990143633
17 : 0.8057037173535592
18 : 0.8056157276346421
19 : 0.8055217412151643
20 : 0.8054229124771045
21 : 0.8053201927252294
22 : 0.8052143709612845
23 : 0.8051061051778503
24 : 0.8049959466859988
25 : 0.8048843592451607
26 : 0.80477173426091
27 : 0.8046584029709453
28 : 0.8045446462980357
29 : 0.8044307028771223
30 : 0.8043167756401226
31 : 0.8042030372516454
32 : 0.8040896346220231
33 : 0.8039766926741173
34 : 0.803864317502593
35 : 0.8037525990355243
36 : 0.8036416132860256
37 : 0.8035314242643511
38 : 0.8034220856074266
39 : 0.8033136419721353
40 : 0.8032061302302584
41 : 0.803099580496198
42 : 0.

In [28]:
for i in range(200,500):
    l1 = Lasso(alpha = i)
    l1.fit(X_train, y_train)
    print(i,":",l1.score(X_test,y_test))

200 : 0.8035400678329621
201 : 0.8035436084668162
202 : 0.8035464186902408
203 : 0.8035484974445002
204 : 0.8035497711629634
205 : 0.8035502778905033
206 : 0.8035500174466153
207 : 0.8035489905058871
208 : 0.8035471970683195
209 : 0.8035446371339117
210 : 0.8035413107026642
211 : 0.8035372177745769
212 : 0.8035323583496496
213 : 0.8035267324278828
214 : 0.8035203400092756
215 : 0.8035131810938289
216 : 0.8035052220046542
217 : 0.8034964872966289
218 : 0.8034869859372875
219 : 0.8034767179266306
220 : 0.8034657544964476
221 : 0.8034540284440662
222 : 0.8034415360740239
223 : 0.8034282773863207
224 : 0.8034142523809576
225 : 0.8033994610579338
226 : 0.8033823370547092
227 : 0.8033415832392397
228 : 0.8032758712723419
229 : 0.803209718974961
230 : 0.8031431280067155
231 : 0.8030760652976621
232 : 0.8030085720796426
233 : 0.8029406089057138
234 : 0.8028722158603679
235 : 0.802800670039616
236 : 0.8027313591316162
237 : 0.8026616530356303
238 : 0.8025915352885142
239 : 0.8025209871599314
24

In [29]:
l2 = Ridge(alpha = 11)
l2.fit(X_train, y_train)
print(l2.score(X_test, y_test))

0.8059967986375096


In [30]:
l2.coef_

array([-1.75832379e+02, -9.99948772e+02, -6.89829538e+02,  1.45676176e+03,
        2.33786631e+03,  4.80345394e+02,  2.33433006e+02, -2.03612707e+00,
        3.94123170e+02,  5.75452390e+02,  1.04296846e+02,  2.06673902e+01,
        1.31053817e+02, -2.28194584e+02])

In [31]:
l1 = Lasso(alpha = 212)
l1.fit(X_train, y_train)
print(l1.score(X_test, y_test))

0.8035323583496496


In [32]:
l1.coef_

array([-1.56166692e+02, -0.00000000e+00, -4.96117523e+02,  9.70365424e+02,
        1.04332524e+03,  2.79881536e+02,  2.97619631e+01,  9.96454509e-01,
        3.28545400e+02,  4.86247919e+02,  1.15357074e+02,  1.62709281e+01,
        0.00000000e+00, -1.11008970e+02])

## K-fold Cross Validation

In [33]:
from sklearn.model_selection import cross_val_score

In [34]:
l1_cross = cross_val_score(l1,X,y,cv = 4)
print(l1_cross)

[0.81527361 0.81973611 0.45385532 0.4386946 ]


In [35]:
np.mean(l1_cross)

0.6318899090861153

In [36]:
l2_cross = cross_val_score(l2,X,y,cv = 4)
print(l2_cross)

[0.78928994 0.86367612 0.43404183 0.44572381]


In [37]:
np.mean(l2_cross)

0.6331829256162267